[phases.setup]
nixPkgs = ["nodejs_20", "mongodb"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production" 